### ISSUE TITLE
Duplicate generation of init

### ISSUE THREAD

**Issue by FranzBusch** [uber/mockolo#106]
When defining a protocol with an `init()` mockolo generates two `init()`s

Example:
```swift
protocol Foo {
    init()
}
```

Output:

```swift
public class FooMock: Foo {
    public init() { 
    required public init() {

    }
}
``` 

Only one `required init` should be generated

**Comment by elsh** [comment]
resolved https://github.com/uber/mockolo/releases/tag/1.2.1
