### ISSUE TITLE
Support for Combine

### ISSUE THREAD

**Issue by vsanthanam** [uber/mockolo#110]
Add support for annotation attributes for Combine subjects and publishers so they too can be easily mocked.

**Comment by elsh** [comment]
@vsanthanam  Per discussion, could you add examples here?

**Comment by vsanthanam** [comment]
When mockolo is mocking a property, is does something special if the property is an `Observable<Element>`

The generated mock will not crash you try to access the property before assignment, and is instead automatically backed `PublishSubject`. An additional ivar is created to allow the consumer to add values to the sequence, and additional options exist to control what kind of subject is used to back the `Observable` (e.g. replay, behavior, etc.)

I think we should add the same functionality when a property is of type `AnyPublisher` (Apple's equivalent of Observable — a ready only, type erased value that the consumer can subscribe to but cannot add values to)

We should also back these types automatically with a combine subject, and provide some controls over what kind of subjects could be used. Unlike Observables which are generics specialized against a single type, Publishers are specialized with two types (the value to emit, as well as the error), so this could add some complexity. On the plus side though, Combine has much fewer features than RxSwift as of now, and only there are only two subject types to choose from.

For example:

```
/// @mockable
protocol StateManaging {
   var myState: AnyPublisher<State, Error>
}
```

Could generate the following mock:

```
class StateManagingMock: StateManaging {
   var myState: AnyPublisher<State, Error> {
      myStateSubject.eraseToAnyPublisher() // the Combine equivalent of `.asObservable()` to perform type erasure of the mutable interface.
   }
   
   var myStateSubject = PassthroughSubject<State, Error>()
}
```

Combine really only has two subjects: PassthroughSubject (the equivalent of PublishSubject, initialized with no arguments), and CurrentValueSubject (the equivalent of BehaviorSubject, initialized with one value to start the sequence), so you'd have full coverage by supporting just those two.
