### ISSUE TITLE
Is there any way to assert function argument histories?

### ISSUE THREAD

**Issue by andooown** [uber/mockolo#111]
I would't like to assert function argument histories like as bellow.
```swift
protocol Foo {
    func fooFunc(_ arg: Int)
    func barFunc(_ arg1: Int, arg2: String)
}

let mock = FooMock()
mock.fooFunc(1)
mock.fooFunc(2)
mock.fooFunc(3)

XCTAssertEqual(mock.fooFuncValues, [1, 2, 3])

mock.barFunc(1, "A")
mock.barFunc(2, "B")
mock.barFunc(3, "C")

XCTAssertEqual(mock.barFuncValues, [(1, "A"), (2, "B"), (3, "C")])
```

Is there any way to achive this? And if I can't do currently, can I contribute to implement this feature?

**Comment by elsh** [comment]
This is currently not supported; contributions are welcome!

Do you want the history to be enabled for all funcs or only for some funcs? 

If the former, you can add an input flag (e.g. --enable-args-history) to the commandline, and support it if the flag is enabled.  

If the latter, you could utilize arguments to the @mockable annotation (e.g. /// @mockable(history: fooFunc = true; barFunc = true)) and support it if listed in the arguments (see 'typealias', 'rx', 'module' in README for other examples).

**Comment by andooown** [comment]
@elsh 
Thanks! I'd like to contribute!

> Do you want the history to be enabled for all funcs or only for some funcs?
> 
> If the former, you can add an input flag (e.g. --enable-args-history) to the commandline, and support it if the flag is enabled.
> 
> If the latter, you could utilize arguments to the @mockable annotation (e.g. /// @mockable(history: fooFunc = true; barFunc = true)) and support it if listed in the arguments (see 'typealias', 'rx', 'module' in README for other examples).

I think the former way is better because it's easy to use.
However, do you have any concerns? (e.g. performance)

**Comment by andooown** [comment]
@tinder-maxwellelliott 
Yes, it's right.

However, we must implement like that many times in some usecases.
For example, my app is built with VIPER architecture and our Presenters output effects to Views/Interactors by calling those functions like as bellow. (In fact, it's more complicated than that.)
In this usecase, using test spy is easy way.

```swift
// Protocols
protocol FooView {
    func setTitle(_ title: String)
}
protocol FooUsecase {
    func getUser(userId: String)
}
protocol FooInteractorDelegate {
    func didGetUser(_ user: User)
}

// Presenter
class FooPresenter {
    private let view: FooView
    private let interactor: FooUsecase

    private let userId: String
    
    init(view: FooView, interactor: FooUsecase, userId: String) {
        self.view = view
        self.interactor = interactor
        self.userId = userId
    }
}

extension FooPresenter {
    func viewDidLoad() {
        interactor.getUser(userId: userId)
    }
}

extension FooPresenter: FooInteractorDelegate {
    func didGetUser(_ user: User) {
        view.setTitle(user.name)
    }
}

// Test
let mockView = FooViewMock()
let mockInteractor = FooUsecaseMock()

let presenter = FooPresenter(view: mockView, interactor: mockInteractor, userId: "foo_user")

presenter.viewDidLoad()
XCTAssertEqual(mockInteractor.getUserValues, ["foo_user"])

let user = User(id: "foo_user", name: "foo")
presenter.didGetUser(user)
XCTAssertEqual(mockView.setTitleValues, ["foo"])
```

And some other mock generators support this feature, for example,  [`ArgumentCaptor`](https://github.com/Brightify/Cuckoo#argument-capture) in [Brightigy/Cuckoo](https://github.com/Brightify/Cuckoo).

I want to use this feature in Mockolo. Maybe I implement this as opt-in.
How about it?

**Comment by elsh** [comment]
> @elsh
> Thanks! I'd like to contribute!
> 
> > Do you want the history to be enabled for all funcs or only for some funcs?
> > If the former, you can add an input flag (e.g. --enable-args-history) to the commandline, and support it if the flag is enabled.
> > If the latter, you could utilize arguments to the @mockable annotation (e.g. /// @mockable(history: fooFunc = true; barFunc = true)) and support it if listed in the arguments (see 'typealias', 'rx', 'module' in README for other examples).
> 
> I think the former way is better because it's easy to use.
> However, do you have any concerns? (e.g. performance)

The only concern is that if you enable this for all funcs, there will be more generated code, thus the compile time of mocks will increase as well, so use it at your discretion. 

I agree with @tinder-maxwellelliott that this can easily be supported in the test code itself as in the example.  However, if you don't want to have to write it for all funcs in the tests and that you have a lot of funcs, we could support this with the optional input flag mentioned above.

**Comment by andooown** [comment]
> > @elsh
> > Thanks! I'd like to contribute!
> > > Do you want the history to be enabled for all funcs or only for some funcs?
> > > If the former, you can add an input flag (e.g. ) to the commandline, and support it if the flag is enabled.
> > > If the latter, you could utilize arguments to the @mockable annotation (e.g. /// @mockable(history: fooFunc = true; barFunc = true)) and support it if listed in the arguments (see 'typealias', 'rx', 'module' in README for other examples).
> > 
> > 
> > I think the former way is better because it's easy to use.
> > However, do you have any concerns? (e.g. performance)
> 
> The only concern is that if you enable this for all funcs, there will be more generated code, thus the compile time of mocks will increase as well, so use it at your discretion.
> 
> I agree with @tinder-maxwellelliott that this can easily be supported in the test code itself as in the example. However, if you don't want to have to write it for all funcs in the tests and that you have a lot of funcs, we could support this with the optional input flag mentioned above.

OK, I also agree with @tinder-maxwellelliott and worry about the compile time of mocks.
So I suggest the flexible way as bellow.

1. By default, generate argument capture with only annotated funcs. (e.g. `/// @mockable(history: fooFunc = true; barFunc = true)`)
1. if passed `--enable-args-history` args, generate argument captures with all funcs and ignore annotations.

How about it?

**Comment by elsh** [comment]
Sounds good. Let me know if you have any questions re: implementation.

**Comment by andooown** [comment]
@elsh Thanks! I'm going to start implementing!

**Comment by andooown** [comment]
@elsh 
Test failed on your latest commit(ec8361f3cd2c400d20e7927ccdec153f8813b6b9).
Were you about to start something?

**Comment by elsh** [comment]
Pull the latest

**Comment by andooown** [comment]
I implemented it in #114!

**Comment by elsh** [comment]
@andooown Thanks for implementing this! 👍   It's been merged to master.

**Comment by andooown** [comment]
@elsh Thanks for your reviews!
