### ISSUE TITLE
Remove sourcekitten from dependencies

### ISSUE THREAD

**Issue by elsh** [uber/mockolo#113]
@devturhan Are you still actively using mockolo via cocoapods?  We're considering removing sourcekitten from dependencies as the other parser (swiftsyntax) is more performant and has been set to default for some time now. If removed, we won't be able to support mockolo via cocoapods any longer, as swiftsyntax is not a pod. You can still use mockolo via other means, mint, brew, etc (see README) but that means you only have access to the commandline, not the APIs.  Let us know; if still actively used, we will instead update the pod version and continue to maintain.

**Comment by devturhan** [comment]
@elsh Nope we are not using it, thanks for asking 🙏

**Comment by elsh** [comment]
No prob! We’ll go ahead and remove sourcekitten then. Thanks.
