### ISSUE TITLE
Swift Package Manager dependency resolution fails

### ISSUE THREAD

**Issue by ashare80** [uber/mockolo#117]
because no versions of mockolo match the requirement 1.2.4..<2.0.0 and package mockolo is required using a version-based requirement and it depends on unversion package swift-tools-support-core, mockolo >=1.2.3 is forbidden.
And because root depends on mockolo 1.2.3..<2.0.0, version solving failed

**Comment by elsh** [comment]
Good catch. Resolved at https://github.com/uber/mockolo/releases/tag/1.2.4.

**Comment by khushbu2892** [comment]
> because no versions of mockolo match the requirement 1.2.4..<2.0.0 and package mockolo is required using a version-based requirement and it depends on unversion package swift-tools-support-core, mockolo >=1.2.3 is forbidden.
> And because root depends on mockolo 1.2.3..<2.0.0, version solving failed
