### ISSUE TITLE
Enhance function arguments history annotation syntax to support multiple functions

### ISSUE THREAD

**Issue by siddarthkalra** [uber/mockolo#123]
The ReadMe states that the following provides the ability to capture function arguments history:

```
/// @mockable(history: fooFunc = true)
public protocol Foo {
    func fooFunc(val: Int)
    func barFunc(_ val: (a: String, Float))
    func bazFunc(val1: Int, val2: String)
}
```

But if I wanted to track the history for multiple functions, say `fooFunc` and `barFunc`, there doesn't seem to be a way to convey that to Mockolo. For e.g. I thought something like this would work but it didn't (I tried a few different variations of the syntax but couldn't get it to work)

```
/// @mockable(history: fooFunc = true, barFunc = true)
public protocol Foo {
    func fooFunc(val: Int)
    func barFunc(_ val: (a: String, Float))
    func bazFunc(val1: Int, val2: String)
}
```

For now, I ended up using `--enable-args-history` but that paints with too broad a brush and it would be nice to have a syntax that can provide more granular control.

**Comment by elsh** [comment]
The delimiter is a semicolon, not a comma. Can you try this?  
 /// @mockable(history: fooFunc = true; barFunc = true)

**Comment by siddarthkalra** [comment]
> The delimiter is a semicolon, not a comma. Can you try this?
> /// @mockable(history: fooFunc = true; barFunc = true)

@elsh the semicolon didn't work for me either. I just tried it in my project and found that the history tracking gets added for the first function but doesn't for the second function. Maybe the script to generate my the code is wrong? I'm using

```
mockolo -s "MyApp" -d "Mocks.generated.swift" -i "MyApp"
```

Can you possibly point me to a unit test or an example project that shows this working?

**Comment by elsh** [comment]
Tests are at https://github.com/uber/mockolo/blob/master/Tests/TestArgumentsHistory/ArgumentsHistoryTests.swift. It actually seems to be generating for all regardless of what's specified. We'll take a look at this.

**Comment by elsh** [comment]
Checked again, and it is actually generating correctly. See `testArgumentsHistoryWithAnnotationNotAllFuncCases` at https://github.com/uber/mockolo/blob/master/Tests/TestArgumentsHistory/FixtureArgumentsHistory.swift. It uses  `enableFuncArgsHistory = false`. 

Example: `argumentsHistoryWithAnnotation` specifies `/// @mockable(history: fooFunc = true; barFunc = true)`.   `argumentsHistoryWithAnnotationNotAllFuncCaseMock` contains `fooFuncArgValues` and `bazFuncArgValues`, but NOT `barFuncArgValues`.  

Your command should work (just a side note: `-i "MyApp"` will generate `@testable import MyApp`; not sure if that's what you intended, but in any case, this shouldn't interfere with func arg history). 

-----

Running your example above with a semicolon delimiter shows the following output:  

```
/// @mockable(history: fooFunc = true; barFunc = true)
public protocol Foo {
    func fooFunc(val: Int)
    func barFunc(_ val: (a: String, Float))
    func bazFunc(val1: Int, val2: String)
}

```

Output: 

```
public class FooMock: Foo {
    public init() { }

    public var fooFuncCallCount = 0
    public var fooFuncArgValues = [Int]()
    public var fooFuncHandler: ((Int) -> ())?
    public func fooFunc(val: Int)  {
        fooFuncCallCount += 1
        fooFuncArgValues.append(val)
        if let fooFuncHandler = fooFuncHandler {
            fooFuncHandler(val)
        }
        
    }

    public var barFuncCallCount = 0
    public var barFuncArgValues = [(a: String, Float)]()
    public var barFuncHandler: (((a: String, Float)) -> ())?
    public func barFunc(_ val: (a: String, Float))  {
        barFuncCallCount += 1
        barFuncArgValues.append(val)
        if let barFuncHandler = barFuncHandler {
            barFuncHandler(val)
        }
        
    }

    public var bazFuncCallCount = 0
    public var bazFuncHandler: ((Int, String) -> ())?
    public func bazFunc(val1: Int, val2: String)  {
        bazFuncCallCount += 1
        if let bazFuncHandler = bazFuncHandler {
            bazFuncHandler(val1, val2)
        }
    }
}

```

Notice the `fooFuncArgValues` and `barFuncArgValues`, but there's no bazFuncArgValues. This is as expected. 
Lmk if you're still seeing issues.

**Comment by elsh** [comment]
Closing now as it works as expected. Feel free to re-open if you're still seeing issues with this.
