### ISSUE TITLE
Impossible to generate mocks by Xcode 12

### ISSUE THREAD

**Issue by imairi** [uber/mockolo#124]
Install mockolo using Xcode 12.0 following the below operation.

```
$ git clone https://github.com/uber/mockolo.git
$ cd mockolo
$ swift build -c release
```

To Generate mocks, run the below command, SwiftSyntax.ParserError is occurred. It is failed to generate mock.

```
.build/release/mockolo -s [MOCK TARGETS]
```

```
Fatal error: The operation couldn’t be completed. (SwiftSyntax.ParserError error 1.): file /Users/vagrant/git/mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/ParserViaSwiftSyntax.swift, line 86
/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise706137049/step_src/._script_cont: line 43:  9133 Illegal instruction: 4  ./mockolo/.build/release/mockolo -s [MOCK TARGETS]
```

This issue may be occurred from Xcode 12.0 beta 1. ( latest beta version as well. )

**Comment by elsh** [comment]
triaged

**Comment by elsh** [comment]
Thanks for your patience. https://github.com/uber/mockolo/releases/tag/1.2.6.

**Comment by schung7** [comment]
I'm still running into this issue on Xcode 12.0 GA.

**Comment by elsh** [comment]
Updated. Please check https://github.com/uber/mockolo/releases/tag/1.2.8 again. Thanks.

**Comment by tinder-swchung** [comment]
@elsh I'm still seeing the same issue even with the latest 1.2.8 release -- works for Xcode 11.6 but not Xcode 12.0.

**Comment by elsh** [comment]
Can you explain the issue? Does it not find a dylib or throws a fatal error when trying to parse?  Also can you make sure you've selected Xcode12 (`sudo xcode-select -s [path]`)?

**Comment by samoilyk** [comment]
@elsh I have this issue with Xcode 12.0 as well. Latest 1.2.8 installed using Homebrew
`Fatal error: The operation couldn’t be completed. (SwiftSyntax.ParserError error 1.): file /private/tmp/mockolo-20200913-24987-c78m47/mockolo-1.2.8/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/ParserViaSwiftSyntax.swift, ...`

**Comment by elsh** [comment]
I see; we'll update brew.

**Comment by tinder-maxwellelliott** [comment]
Brew looks up to date @elsh, see here https://github.com/Homebrew/homebrew-core/blob/4ded1b91f36c4c68ce8aaf89dfd93c7cea526d58/Formula/mockolo.rb

**Comment by elsh** [comment]
Xcode version is still set to 11.4.  Doesn't that need to be changed to 12.0 manually?  Package.swift in Mockolo is now updated to use Swift 5.3 / Xcode 12.0 by default.

**Comment by tinder-maxwellelliott** [comment]
> Xcode version is still set to 11.4. Doesn't that need to be changed to 12.0 manually? Package.swift in Mockolo is now updated to use Swift 5.3 / Xcode 12.0 by default.

Ill make a PR for this

**Comment by tinder-maxwellelliott** [comment]
PR is up, but Xcode 12 is not on the Homebrew boxes yet https://github.com/Homebrew/homebrew-core/pull/61491

**Comment by elsh** [comment]
Thanks for putting up the PR.  Do you know how long it usually takes them to update their env?

**Comment by elsh** [comment]
@tinder-maxwellelliott  Would you be able to update brew with https://github.com/uber/mockolo/releases/tag/1.2.9 when you have time? Do you happen to know which Xcode 12 version is on brew CI boxes?

**Comment by elsh** [comment]
Please reopen if this is still an issue.

**Comment by bezoadam** [comment]
I have same error now with Xcode 13.3 and mockolo version 1.7.0 😕

**Comment by developer-9** [comment]
I'm still running into this issue on Xcode 13.3.1 using mockolo 1.7.0!
