### ISSUE TITLE
Avoid writing to destination file if content is unchanged

### ISSUE THREAD

**Issue by ffittschen** [uber/mockolo#131]
We recently investigated our build times and discovered that `mockolo` [is always writing](https://github.com/uber/mockolo/blob/7439d3b6f40f2169752825296fd5712cdd137ae2/Sources/MockoloFramework/Operations/OutputWriter.swift#L44) to the destination file even though the content did not change. This behavior will trigger Xcode to rebuild modules in which no source code was changed (and all of the modules that depend on this module). To improve this behavior, I'd suggest to check if the destination file already exists and only write the file if the content is unchanged.

To test the current behavior, I executed these commands:
```bash
stat Sources/Mocks.generated.swift
mockolo -s Sources/ -d Sources/Mocks.generated.swift -m DEBUG
stat Sources/Mocks.generated.swift
```

Looking at other tools that generate code, they also avoid to write the destination file if the content is unchanged. (See [SwiftGen](https://github.com/SwiftGen/SwiftGen/blob/stable/Sources/SwiftGen/Commander/OutputDestination.swift#L32-L44) or [R.swift](https://github.com/mac-cain13/R.swift/blob/master/Sources/RswiftCore/RswiftCore.swift#L180-L188))

If you accept this suggestion, I'd be happy to open a PR for this.

**Comment by elsh** [comment]
Sorry for a delay. Left a comment on your PR.
