### ISSUE TITLE
Is private(set) really desirable?

### ISSUE THREAD

**Issue by FranzBusch** [uber/mockolo#133]
We just upgraded our mockolo version and saw a bunch of build failures because we were resting the generated `callCount` properties during tests. This was necessary in our tests because of two reasons:

1. To remove any unnecessary calls that happen during a test case setup
2. If you mock a protocol with static methods, then you need to manually reset them between each test

Would it make sense to make this configurable in mockolo and for the case of the static method maybe even disable it by default?

**Comment by elsh** [comment]
We can make it configurable. How soon would you need this? Also feel free to push a PR if possible. Our ETA is within the next couple of weeks.

**Comment by FranzBusch** [comment]
@elsh not super critical for us right now. We just quickly changed the code that was making use of this.

I would like to understand the reasoning why making it private in the first place is desirable.

**Comment by marciniwanicki** [comment]
I think `private(set)` might be quite useful to ensure the internal mock state is not accidentally tempered by the tests. If the mock needs to be reused or brought to the initial state, a `resetMock()` (or similar) method could be an alternative to ensure all of the properties are getting into the initial state.

**Comment by FranzBusch** [comment]
A method to reset the mock sounds reasonable and even better than manually zeroing the counts.

**Comment by elsh** [comment]
Reset is a great idea, but in this case, it actually takes less bookkeeping (thus simpler) to configure setting vars directly via an input flag.  See if https://github.com/uber/mockolo/releases/tag/1.3.1 resolves your scenario. If needed we can revisit a reset function in the future.

**Comment by FranzBusch** [comment]
@elsh Thanks a lot for the quick help here! Really appreciated
