### ISSUE TITLE
Support for `weak` mock properties

### ISSUE THREAD

**Issue by tinder-maxwellelliott** [uber/mockolo#139]
I would like to be able to specify that certain properties should be generated with the `weak` annotation. What would be a good way to add this to Mockolo's capabilities?

**Comment by EspressoCup** [comment]
There's a 'typealias' override parameter you can pass in to the @mockable(..) argument for associatedtypes. You could something similar, i.e. create another override parameter 'attribute', and specify the var name and what its attribute should be, like so: 

/// @mockable(attribute: foo = weak; bar = dynamic) 
protocol P {
   var foo: SomeType? { get } 
   var bar: String { get }  
}

**Comment by HermanKayy** [comment]
@EspressoCup is this something you can add support for? Love to be able to use this

**Comment by tinder-garricnahapetian** [comment]
+1

This would be great.

**Comment by EspressoCup** [comment]
Unfortunately my timeline is tbd. I can help with code reviews if anyone has a bandwidth to work on PRs if this is a pressing issue.
