### ISSUE TITLE
Fail to generate mock with protocol inheritance

### ISSUE THREAD

**Issue by keithcml** [uber/mockolo#146]
Our team is also using RIBs as our app architecture.
When using Mockolo to generate mock for RootInteractable, the parent protocol methods, Interactable and InteractorScope, cannot be generated.

Example:
```
protocol RootInteractable: Interactable {
    var router: RootRouting? { get set }

    func someMethod()
}
```

Generated codes:
```
class RootInteractableMock: RootInteractable {
    init() { }
    init(router: RootRouting? = nil) {
        self.router = router
    }


    private(set) var routerSetCallCount = 0
    var router: RootRouting? = nil { didSet { routerSetCallCount += 1 } }

    private(set) var someMethodCount = 0
    func someMethod()  {
        someMethodCount += 1        
    }
}
```

![image](https://user-images.githubusercontent.com/5032142/118114117-bf347400-b419-11eb-959d-5bd9fe8ead67.png)

I am using the latest downloaded binary and Xcode 12.4.

I think the problem is Interactor is the protocol in RIBs module. And Mockolo seems cannot mock from external module.

**Comment by keithcml** [comment]
<img width="376" alt="image" src="https://user-images.githubusercontent.com/5032142/118218279-b7bcab80-b4a9-11eb-8b76-d178ebb08d2c.png">

I can do the mock on the class of RootInteractor instead of the protocol.

But in this way, the RootInteractor class cannot mark the final keyword on it.

**Comment by EspressoCup** [comment]
If RootInteractable and Interactable are in two different modules, they both need to be annotated with /// @mockable.

**Comment by keithcml** [comment]
@EspressoCup That means I need to folk the RIBs repo and update for our own use? Is there any way that framework user can annotate instead of waiting for module maker to do it.

**Comment by EspressoCup** [comment]
I should've asked this question first: are you building mocks per module (run mockolo for each target) or for the entire app (run mockolo once for your entire codebase)? My previous comment applies to the former. If the latter, only the child protocol needs to be annotated.  

If the former, you have the following options. 
1. Fork and add annotations yourself as you mentioned.
2. Declare all of the members of the parent protocol in your child protocol (where you annotate /// @mockable). 
3. Create a manual mock class for each parent protocol and pass the mock files in as 'processed' files in the mock generator.

The option #2 is probably most straightforward. Lmk if that helps.

**Comment by keithcml** [comment]
My situation is, I have 2 frameworks, A depends on B. I have a protocol in B (aka ProtocolB).
```
protocol ProtocolB {
  func thisIsB()
}
```

In Framework A, I have also had a protocol, inherit ProtocolB.
```
protocol ProtocolA: ProtocolB {
  func thisIsA()
}
```

Then I write unit tests on Framework A. Only ProtocolA methods generated for ProtocolAMock.
```
class ProtocolAMock: ProtocolA {
  func thisIsA() {}

  // missing thisIsB() and there is compile error.
}
```

Is it the expected behavior? @EspressoCup

**Comment by EspressoCup** [comment]
@keithcml Are you building mocks per module (run 'mockolo' for each target) or for the entire app (run 'mockolo' once for your entire codebase)?
