### ISSUE TITLE
System requirements out of date?

### ISSUE THREAD

**Issue by carlocab** [uber/mockolo#147]
Your README states that the [system requirements](https://github.com/uber/mockolo/blob/daeef22ad8da44e775d1f4dd007a181594361699/README.md#system-requirements) are met by Swift 5.2, Xcode 11.4, and macOS 10.14.6.

However, it seems that your latest tagged release seems to require Swift 5.4,

https://github.com/uber/mockolo/blob/e723dc2360398e402ffcb0d8ce8c988d675f6c32/Package.swift#L4-L8

which requires a bit more than your stated system requirements.

Is your README just outdated? I just wanted to confirm for https://github.com/Homebrew/homebrew-core/pull/76261. Thanks!

**Comment by EspressoCup** [comment]
The requirements are now updated.

**Comment by carlocab** [comment]
Thank you very much.
