### ISSUE TITLE
Mock generation aborts with "image not found"

### ISSUE THREAD

**Issue by jpsoultanis** [uber/mockolo#149]
`brew install mockolo`

`mockolo -s myDir -d ./GeneratedMocks.swift`
```
dyld: Library not loaded: @rpath/lib_InternalSwiftSyntaxParser.dylib
  Referenced from: /usr/local/bin/mockolo
  Reason: image not found
Abort trap: 6
```

**Comment by jpsoultanis** [comment]
I tried renaming my Xcode app to "Xcode.app" and running `xcode-select -s MY_DIRECTORY` and now I get a new error:

```
Start...
["Process input mock files..."]
["Took", 0.0001150369644165039]
["Process source files and generate an annotated/protocol map..."]
Fatal error: The operation couldn’t be completed. (SwiftSyntax.ParserError error 1.): file MockoloFramework/SourceParser.swift, line 101
Illegal instruction: 4
```

**Comment by maxwellE** [comment]
Brew is notoriously bad about managing these kinds of relationships between Xcode, the SwiftSyntax dylib and this library. I think we should open a ticket on homebrew for this issue since I am able to use `swift run mockolo`, meaning there is no issue in the source code

**Comment by uhooi** [comment]
It does not appear to be a Mockolo problem, so I will close it.
