### ISSUE TITLE
Replace swift-tools-support-core with swift-argument-parser

### ISSUE THREAD

**Issue by uhooi** [uber/mockolo#151]
ArgumentParser in swift-tools-support-core is deprecated, should be replaced by swift-argument-parser.  
ref: https://github.com/apple/swift-tools-support-core/pull/194

**Comment by pejato** [comment]
I can take this on. I already have most of it done. I need to do some validation and write some tests if/where possible and then it should be ready.

**Comment by pejato** [comment]
Looks like I didn't tag this issue correctly in my PR to fix this, but this should be resolved by #153

**Comment by uhooi** [comment]
Thank you very much!!
I close this issue.
