### ISSUE TITLE
Could you cut a release with Combine support?

### ISSUE THREAD

**Issue by adam-zethraeus** [uber/mockolo#159]
@EspressoCup Thanks so much for merging @milettal's Combine PR https://github.com/uber/mockolo/pull/155
(and thanks for the functionality, @milettal!)

Whenever it makes sense for you all, would you be able to cut a release? 
(No presh. I'll just use https://github.com/ConsultingMD/mockolo until then :) )

Also, miss y'all peeps.  <3

**Comment by alanzeino** [comment]
yes

**Comment by alanzeino** [comment]
p.s. miss you adam

**Comment by EspressoCup** [comment]
Released https://github.com/uber/mockolo/releases/tag/1.5.0
