### ISSUE TITLE
Cont. on #146 Fail to generate mock with protocol inheritance

### ISSUE THREAD

**Issue by keithcml** [uber/mockolo#167]
#146 
@EspressoCup Sorry for disturbing you again.

**Comment by EspressoCup** [comment]
You'll need to pass a --mockfiles input option with paths to files that contain mocks of protocols that you inherit (which live in different modules). Please see test examples at https://github.com/uber/mockolo/blob/master/Tests/TestOverloads/OverloadTests.swift - testOverloadInParent, testOverloadInParentAndChild, or any tests that have the `mockContent:` parameter; this is used to pass in the file content for the --mockfiles option, and you should be able to see how it's used by stepping through the implementation with a debugger.

**Comment by keithcml** [comment]
thanks @EspressoCup . let me have a try first

**Comment by RoryKelly** [comment]
For anyone else looking for a solution

**Comment by keithcml** [comment]
It works !

**Comment by uhooi** [comment]
It looks fine, so I will close it.
