### ISSUE TITLE
iOS project with mockolo 1.6.2 fails to build.

### ISSUE THREAD

**Issue by betat** [uber/mockolo#168]
## Details

I use mockolo in iOS project with using [Mint](https://github.com/yonaskolb/Mint), and manage mockolo version with `Mintfile` .
With version 1.6.1 of mockolo, the iOS project builds successfully, but if specify the version to 1.6.2, an error occurs and the build does not succeed.

### Error Message
```
MockoloFramework/SourceParser.swift:101: Fatal error: The operation couldn’t be completed. (SwiftSyntax.ParserError error 1.)
```

### OS version
macOS 11.6.1

### Swift version installed on my machine
Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)

### Xcode version
Xcode 12.5.1

### PMs version
```sh
$ brew --version
Homebrew 3.3.6
Homebrew/homebrew-core (git revision df0e94b2a93; last commit 2021-12-02)
Homebrew/homebrew-cask (git revision 6c3d470278; last commit 2021-12-02)
```

```sh
$ brew info mint
mint: stable 0.17.1 (bottled)
```

### mockolo Version
https://github.com/uber/mockolo/releases/tag/1.6.2

### Compare 1.6.1 and 1.6.2
https://github.com/uber/mockolo/compare/1.6.1...1.6.2

**Comment by uhooi** [comment]
@betat
I have not changed SwiftSyntax in 1.6.2, so I think there is another cause.
Could you please delete the cache of Mint etc. and try again?

**Comment by betat** [comment]
@uhooi 

Thank you for your reaction!
I solved this issue!!

I took the following actions.
* Check the current Xcode version -> `$ xcode-select -p`
* Delete Devived Data of Xcode 12.5.1
* `mint uninstall mockolo` and `mint bootstrap`
* Rebuild (and Build Succeeded!)

**Comment by uhooi** [comment]
@betat 
I'm happy because you solved the problem :)

The reporting of the problem was very clear.
I'll be referring to it as well!!
