### ISSUE TITLE
Support RXSwift Traits: Single, Completable, Maybe, 

### ISSUE THREAD

**Issue by saltyskip** [uber/mockolo#174]
Is there any chance to support RXSwift trait types Single, Completable, and Maybe? I believe they would be handled in mostly the same way as the existing observables.

https://github.com/ReactiveX/RxSwift/blob/main/Documentation/Traits.md#rxswift-traits

**Comment by sidepelican** [comment]
Adding such a feature is not currently planned. However, a PR will be accepted if there is a case where it is absolutely necessary to have it.
