### ISSUE TITLE
Xcode 13.2.1 warns on /// @mockable annotations

### ISSUE THREAD

**Issue by adam-zethraeus** [uber/mockolo#176]
<img width="657" alt="CleanShot 2022-02-03 at 12 46 54@2x" src="https://user-images.githubusercontent.com/509838/152435683-7250824b-0f78-4b0a-aa4e-662e882ce3d0.png">

I guess it's trying to be nice and tell you what doesn't work in [DocC](https://developer.apple.com/documentation/xcode/formatting-your-documentation-content). 

Although, given DocC's /// standard, would it be worth making the annotations semantic within it? 
```swift
/// > Tip: Mockable(combine: fooPublisher = PassthroughSubject; barPublisher = CurrentValueSubject)
```

**Comment by adam-zethraeus** [comment]
(If you like the suggestion, LMK an I'll try taking it on)

**Comment by EspressoCup** [comment]
Yup go for it 👍
