### ISSUE TITLE
Release 1.7.0 is missing the binary

### ISSUE THREAD

**Issue by mhdabdulhameed** [uber/mockolo#188]
The latest release of Mockolo doesn't have the binary attached in the GitHub release. I think it would be great to have it attached :)

![Screenshot 2022-06-03 at 11 28 42](https://user-images.githubusercontent.com/22226689/171828258-3c6c1f31-1617-4aa0-a1b4-739eb8670c19.png)

**Comment by EspressoCup** [comment]
To create a binary, run https://github.com/uber/mockolo/blob/master/install-script.sh with input target name `mockolo` and output `mockolo.tar.gz`.
