### ISSUE TITLE
Mock generation fails when loading lib_InternalSwiftSyntaxParser.dylib

### ISSUE THREAD

**Issue by fummicc1** [uber/mockolo#194]
## What Happened

Hello, I am new to mockolo but this library is very great as a mock generator. After I installed mockolo via [Mint](https://github.com/yonaskolb/Mint), I ran the following [run comamnd](#run-command) from Terminal and got the [error log](#log).

## Environments

- M1 MacbookAir
- macOS: Ventura
- Xcode: Version 14.0 beta 2 (14A5229c)
- mockolo: 1.7.0
- mint: 0.17.1

## Run Command

```
mint run mockolo -s ./Pog/Pog -d ./Pog/Pog/Mock/Generated
```

## Log

```
🌱 Finding latest version of mockolo
🌱 Running mockolo 1.7.0...
dyld[30649]: Library not loaded: @rpath/lib_InternalSwiftSyntaxParser.dylib
  Referenced from: <567E5949-DBDB-340F-8C8A-FC61515EE9DC> /Users/fumiyatanaka/.mint/packages/github.com_uber_mockolo/build/1.7.0/mockolo
  Reason: tried: '/Users/fumiyatanaka/.mint/packages/github.com_uber_mockolo/build/1.7.0/lib_InternalSwiftSyntaxParser.dylib' (no such file),
 '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/macosx/lib_InternalSwiftSyntaxParser.dylib' (no such file), 
'/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/macosx/lib_InternalSwiftSyntaxParser.dylib' (no such file), 
'/Users/fumiyatanaka/.mint/packages/github.com_uber_mockolo/build/1.7.0/lib_InternalSwiftSyntaxParser.dylib' (no such file), 
'/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/macosx/lib_InternalSwiftSyntaxParser.dylib' (no such file), 
'/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/macosx/lib_InternalSwiftSyntaxParser.dylib' (no such file), 
'/System/Volumes/Preboot/Cryptexes/OS@rpath/lib_InternalSwiftSyntaxParser.dylib' (no such file), 
'/Users/fumiyatanaka/.mint/packages/github.com_uber_mockolo/build/1.7.0/lib_InternalSwiftSyntaxParser.dylib' (no such file), 
'/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/macosx/lib_InternalSwiftSyntaxParser.dylib' (no such file), 
'/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/macosx/lib_InternalSwiftSyntaxParser.dylib' (no such file), 
'/Users/fumiyatanaka/.mint/packages/github.com_uber_mockolo/build/1.7.0/lib_InternalSwiftSyntaxParser.dylib' (no such file), 
'/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/macosx/lib_InternalSwiftSyntaxParser.dylib' (no such file), 
'/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/macosx/lib_InternalSwiftSyntaxParser.dylib' (no such file),
 '/usr/local/lib/lib_InternalSwiftSyntaxParser.dylib' (no such file), 
'/usr/lib/lib_InternalSwiftSyntaxParser.dylib' (no such file, not in dyld cache)
```

## Working Directory

<img width="1134" alt="スクリーンショット 2022-07-09 10 40 51" src="https://user-images.githubusercontent.com/44002126/178086924-b6d37fbb-801b-4108-a16b-62c018aa90b4.png">

**Comment by fummicc1** [comment]
Note:
I think this error occures when swift toolchain is for Swift 5.7. Because I can generate mock by re-compiling mockolo locally, where Xcode14 beta is installed.

Tips:
I can avoid this error by the following way.

1. Clone this mockolo repository
2. Run `swift build -c release` with current directory `mockolo`. (Notice that `xcodebuild -p` shows Xcode14 beta path.)
3. run executable file.

**Comment by sidepelican** [comment]
This should be fixed by mint.
mockolo has dependency of `@rpath/lib_InternalSwiftSyntaxParser.dylib`(you can check this by `otool -L <your/mockolo/path>`) , and `swift build` puts `lib_InternalSwiftSyntaxParser.dylib` to the same directory to `mockolo`.
mint copies `mockolo` to mint's cache directory but doesn't copy  `lib_InternalSwiftSyntaxParser.dylib`. so `lib_InternalSwiftSyntaxParser.dylib` cannot found with `@rpath`.

**Comment by fummicc1** [comment]
Thank you, sidepelican, for your reply.
Actually I am not familiar with dylib, so I am probing the origin of that problem. (I think `install_name_tool` may be helpful 👀 to overwrite `rpath` of dylib... or I have mint directly copy all files in `@executable_path` to `.mint/packages/.../build` folder.)

**Comment by fummicc1** [comment]
@sidepelican @uhooi @sidepelican 

I realized the origin of this error is that `swift-syntax` for swift5.6  is used in `mockolo`, and swift syntax is developing `relase/5.7` with the head commit https://github.com/apple/swift-syntax/commit/4f33e361829415ab913778a582eda3ad682f81c1.

---

That's why mockolo needs to upgrade swift-syntax to  `release/swift5.7` or wait until `0.5.07...` tag of swift-syntax is branched out before releasing mockolo for Xcode14.🙇‍♂️

**Comment by fummicc1** [comment]
@sidepelican @uhooi @yutailang0119 

I realized the origin of this error is that `swift-syntax` for swift5.6  is used in `mockolo`, and swift syntax is developing `relase/5.7` with the head commit https://github.com/apple/swift-syntax/commit/4f33e361829415ab913778a582eda3ad682f81c1.

---

That's why mockolo needs to upgrade swift-syntax to  `release/swift5.7` or wait until `0.5.07...` tag of swift-syntax is branched out before releasing mockolo for Xcode14.🙇‍♂️

**Comment by fummicc1** [comment]
<img width="1440" alt="スクリーンショット 2022-08-20 4 07 40" src="https://user-images.githubusercontent.com/44002126/185697472-956884a7-b41b-4dbf-944a-4a3e563da43a.png">

I captured the point of using swift-syntax 0.506 tag, this point needs to be swift syntax 0.507 tag when supporting Xcode14, I think.
