### ISSUE TITLE
1.8.0 Release on Brew blocked by failing tests: on arm64 lib_InternalSwiftSyntaxParser.dylib not found

### ISSUE THREAD

**Issue by n-belokopytov** [uber/mockolo#206]
Hey there, I've just found out that the 1.8.0 has not been released on brew. Here is the pipeline:
https://github.com/Homebrew/homebrew-core/actions/runs/3349028971/jobs/5548712516

I am not an iOS engineer, so I have no idea where to look for the problem. Can anyone support?

Seems like test 12 cannot find a lib for arm64:
**Library not loaded: '@rpath/lib_InternalSwiftSyntaxParser.dylib**

Below is the full output of the test
> ==> /opt/homebrew/Cellar/mockolo/1.8.0/bin/mockolo -srcs /private/tmp/mockolo-test-20221028-88859-1qsmth7/testfile.swift -d /private/tmp/mockolo-test-20221028-88859-1qsmth7/GeneratedMocks.swift
  dyld[88874]: Library not loaded: '@rpath/lib_InternalSwiftSyntaxParser.dylib'
    Referenced from: '/opt/homebrew/Cellar/mockolo/1.8.0/bin/mockolo'
    Reason: tried: '/usr/lib/swift/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/opt/homebrew/Cellar/mockolo/1.8.0/bin/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/macosx/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/usr/lib/swift/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/opt/homebrew/Cellar/mockolo/1.8.0/bin/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/macosx/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/usr/local/lib/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/usr/lib/lib_InternalSwiftSyntaxParser.dylib' (no such file)
  Error: mockolo: failed
  An exception occurred within a child process:
    BuildError: Failed executing: /opt/homebrew/Cellar/mockolo/1.8.0/bin/mockolo -srcs /private/tmp/mockolo-test-20221028-88859-1qsmth7/testfile.swift -d /private/tmp/mockolo-test-20221028-88859-1qsmth7/GeneratedMocks.swift
  /opt/homebrew/Library/Homebrew/formula.rb:2500:in `block in system'
  /opt/homebrew/Library/Homebrew/formula.rb:2436:in `open'
  /opt/homebrew/Library/Homebrew/formula.rb:2436:in `system'
  /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/mockolo.rb:28:in `block in <class:Mockolo>'
  /opt/homebrew/Library/Homebrew/formula.rb:2275:in `block (3 levels) in run_test'
  /opt/homebrew/Library/Homebrew/utils.rb:605:in `with_env'
  /opt/homebrew/Library/Homebrew/formula.rb:2274:in `block (2 levels) in run_test'
  /opt/homebrew/Library/Homebrew/formula.rb:967:in `with_logging'
  /opt/homebrew/Library/Homebrew/formula.rb:22[73](https://github.com/Homebrew/homebrew-core/actions/runs/3349028971/jobs/5548712516#step:6:75):in `block in run_test'
  /opt/homebrew/Library/Homebrew/mktemp.rb:[77](https://github.com/Homebrew/homebrew-core/actions/runs/3349028971/jobs/5548712516#step:6:79):in `block in run'
  /opt/homebrew/Library/Homebrew/mktemp.rb:77:in `chdir'
  /opt/homebrew/Library/Homebrew/mktemp.rb:77:in `run'
  /opt/homebrew/Library/Homebrew/formula.rb:2551:in `mktemp'
  /opt/homebrew/Library/Homebrew/formula.rb:2267:in `run_test'
  /opt/homebrew/Library/Homebrew/test.rb:45:in `block in <main>'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:[93](https://github.com/Homebrew/homebrew-core/actions/runs/3349028971/jobs/5548712516#step:6:95):in `block in timeout'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
  /opt/homebrew/Library/Homebrew/test.rb:50:in `<main>'

**Comment by slightair** [comment]
Fixed https://github.com/Homebrew/homebrew-core/pull/116229

But, command shows old version.
Please update Version.swift with the next version. mockolo contributors.
https://github.com/uber/mockolo/blob/1.8.0/Sources/MockoloFramework/Version.swift#L6
