### ISSUE TITLE
SwiftSyntax 508.0.0

### ISSUE THREAD

**Issue by sidepelican** [uber/mockolo#226]
SwiftSyntax 508.0.0 has been released 🎉
https://github.com/apple/swift-syntax/releases/tag/508.0.0

The new version has no dependencies to lib_InternalSwiftSyntaxParser.dylib and has good portability.
I think it would solve whole installation problems.

**Comment by sidepelican** [comment]
Maybe we can remove legacy version support because mockolo already does not have dependency to local toolchain (from SwiftSyntax 0.50700.1).

**Comment by fummicc1** [comment]
🎉
I think we can replace all of `SwiftSyntaxParser` with `SwiftParser` (maybe typealias is fine?)

```swift
#if swift(<5.8)
typealias SwiftParser = SwiftSyntaxParser
#endif
```

but https://github.com/apple/swift-syntax/tree/508.0.0/Sources/SwiftParser says SwiftParser is not fully compatible with SwiftSyntaxParser.
