### ISSUE TITLE
Mock of class with computed properties causes compile error.

### ISSUE THREAD

**Issue by kaniza** [uber/mockolo#245]
Generating a mock of a class with the following properties will result in a compile-time error in the callCount section.

var isOpen:Bool {
    return true
}

Error:. 
Cannot observe read-only property 'isOpen'; it can't change

The relevant code is this part:
override var isOpen: Bool { didSet { isOpenSetCallCount += 1 }

I think callCount is not necessary for read-only Computed Property.

mockolo: 2.0.0 (latest in Homebrew)
macOS 13.5
Swfit: 5.8.1
Xcode: 14.3.1

**Comment by sidepelican** [comment]
Solved with #267
