### ISSUE TITLE
Add build tool plugin

### ISSUE THREAD

**Issue by uhooi** [uber/mockolo#246]
ref: https://github.com/apple/swift-evolution/blob/main/proposals/0303-swiftpm-extensible-build-tools.md

**Comment by sidepelican** [comment]
An artifactbundle is required to use mockolo as a buildToolsPlugin.

This is an example of releasing mockolo as an artifactbundle. It is working.
https://github.com/sidepelican/mockolo/releases/tag/2.0.1

However, it is troublesome to make this automatically by GitHub Actions. Please someone implement it.

**Comment by sidepelican** [comment]
available on 2.1.1
