### ISSUE TITLE
Support for Typed throws

### ISSUE THREAD

**Issue by sutakahashi1** [uber/mockolo#261]
Please add support for Typed throws as described in [SE-0413](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0413-typed-throws.md).

For example:

```swift
func throwsAnything() throws(any Error) { ... }
```

Thank you.

**Comment by fummicc1** [comment]
This feature is introduced in #267 and #262 . Please try it.

**Comment by wvteijlingen-npo** [comment]
Thanks for introducing  this feature! Would it be possible to make a new official release containing this change? Right now we're blocked from using mockolo from homebrew, because that version doesn't support typed throws yet.
