### ISSUE TITLE
CocoaPods Support

### ISSUE THREAD

**Issue by omerturhan** [uber/mockolo#55]
Hi 

I would like to implement CocoaPods support for the mockolo. 
Is it possible for you to add zipped executable to the release files? 

Thanks.

**Comment by elsh** [comment]
CocoaPods support would be useful for a library support but this tool can just run as a command line executable.  Could you provide a use case where CocoaPods would be needed?

**Comment by devturhan** [comment]
I would like to add Mockolo execution to build phases without putting mockolo binary to the repo or forcing other developers to download the binary. Also, I don't want to put generated code to the repository. So the best way to handle this is by adding it as dependency to the dependency manager.

Also, tools like Sourcery and Swiftlint has that support for exactly this reason.

**Comment by elsh** [comment]
Ok sounds good. Will add support for it.

**Comment by elsh** [comment]
Waiting on https://github.com/CocoaPods/CocoaPods/issues/9471.
