### ISSUE TITLE
How to generate mock for protocol includes macro

### ISSUE THREAD

**Issue by imairi** [uber/mockolo#75]
Protocol includes macro, the method is not generated to mock result file. Is there a way to resolve this situation ?

```
protocol PresentableListener: class {
    func run()
    #if DEBUG
    func showDebugMode()
    #endif
}
```

If generate mock for the above protocol, Mock class includes `run` method but `showDebugMode` method is not generated.

**Comment by elsh** [comment]
Can you mention what commandline you used to generate mocks? If you weren't using a commandline, can you mention which of the two parsers (sourcekit, swiftsyntax) was used?

**Comment by imairi** [comment]
@elsh 

```
./mockolo  -s [some directories] -d ./Mock/MockResults.swift --header "@testable import mymodule"
```

I generated mockolo binary and use it like the above command.

**Comment by elsh** [comment]
See https://github.com/uber/mockolo/pull/82

**Comment by imairi** [comment]
@elsh 
I confirmed to generate the mocks includes macro syntax, it works. Thanks for quickly fixing.
