### ISSUE TITLE
Can we create a new tag release?

### ISSUE THREAD

**Issue by maxwellE** [uber/mockolo#78]
@elsh I need a new tag release with this change https://github.com/uber/mockolo/pull/76

**Comment by elsh** [comment]
Let's wait till https://github.com/uber/mockolo/pull/79 is merged. Feel free to add yourself to the reviewer list (I tried to add you but it couldn't seem to find).

**Comment by elsh** [comment]
https://github.com/uber/mockolo/releases/tag/1.1.3
