### ISSUE TITLE
Support imports wrapped in macros

### ISSUE THREAD

**Issue by FranzBusch** [uber/mockolo#83]
Brought up in this PR: #82 

We have the use-case where we have certain import statements wrapped in `#if` macros to only import them in e.g. debug builds. Mockolo is right now picking up every branch it would be great if it would retain the macros in the generated code as well.

**Comment by elsh** [comment]
Triaged

**Comment by elsh** [comment]
resolved https://github.com/uber/mockolo/releases/tag/1.2.1
