### ISSUE TITLE
Ability to add custom imports

### ISSUE THREAD

**Issue by FranzBusch** [uber/mockolo#84]
It would be great to have the ability to add custom imports which can be passes trough a command line option.

Background:
Let's say we have module `A` and the respective test target `ATests`. If we want to put the generated mocks from `A` into the `ATests` target it will miss the `@testable import A` at the top and won't compile.

Maybe you could also explain where you suggest to put the generated mocks. Into the target `A` or the test target `ATests` or rather into a separate target. Would be great if you can share some best practices from your experience.

Especially when you need to use mocks from different modules to write a unit test.

**Comment by SebastianBoldt** [comment]
I experienced the same issue today. I also don't want to add all the protocols, we want to mock, to the test target. You can accomplish this by using the --header parameter.

`mockolo --header "@testable import YourModuleName"`

@FranzBusch If you are looking for another mocking/stubbing Framework which is capable of those things you could also use Cuckoo. It's more powerful that Mockolo.

**Comment by elsh** [comment]
@FranzBusch  We will add custom imports as a separate input option; in the meantime the --header option should unblock you as suggested above.  

Re: best practices, putting mocks in a separate target is probably the cleanest. Alternatively you can put mocks in a module (with #if macro guard around the mocks content) and import it in tests.  Putting mocks in a test target is ok as long as you don't need them in a different test target (you'll need to import the test module in that case).

**Comment by FranzBusch** [comment]
@elsh Thanks for your feedback. We came to the same conclusions and we put the mocks into the main target now with a macro around them.

**Comment by elsh** [comment]
https://github.com/uber/mockolo/pull/86

**Comment by maxwellE** [comment]
Fixed in #89
