### ISSUE TITLE
Header "-h" option does not work as intended

### ISSUE THREAD

**Issue by marciniwanicki** [uber/mockolo#87]
According to the documentation, "-h" should allow to specify header documentation (or even some imports if needed https://github.com/uber/mockolo/issues/84). 

```sh
  --header, -h              A custom header documentation to be added to the beginning of a generated mock file.
```

Looks, it conflicts with the "help" command built into SwiftPM ArgumentParser, in which case the "help" command takes precedence and generation does not start.

Some possible solutions:
- rename short name, i.e. `--header, -hr`
- remove short name, i.e. `--header` (only)

**Comment by elsh** [comment]
Good catch! Will drop the short name for that; or feel free to send a pr with the short name removed.

**Comment by elsh** [comment]
https://github.com/uber/mockolo/pull/90 merged.

**Comment by marciniwanicki** [comment]
Many thanks @elsh !
