### ISSUE TITLE
Understanding the -mocks flag

### ISSUE THREAD

**Issue by FranzBusch** [uber/mockolo#88]
I wanted to use the `-mocks` flag to avoid generating some mocks twice for a module that depended on another one. Maybe I misunderstood the usage of the flag. I have the following scenario:

ModuleA
```swift
import ModuleB

/// @mockable
public protocol ProtocolA: ProtocolB {}
```

ModuleB
```swift
/// @mockable
public protocol ProtocolB {
    func foo()
}

/// @mockable
protocol InternalProtocol {}
```

Now I run a generate command for both targets. For ModuleB everything is fine and it generated the right mocks. However in ModuleA it generated mocks for the `InternalProtocol` as well. However this fails since it cannot see the internal protocol and fails to compile.

I guess this is a pretty common scenario especially in the RIB use case as well where one has to import use the files of the dependencies to generate proper mocks but doesn't won't to generate mocks for them twice.

Am I using the `-mocks` option wrong or is there anything else I could use to reference files/folders which are scanned and used for inheritance etc. but not used to generate actual mocks. @elsh

**Comment by elsh** [comment]
The -mocks option takes in a list of files that contain output mock _classes_ of other modules. These mock classes are then used to resolve inheritance for the current module in case accessing protocols in those other modules is not possible. This applies only if you're building mocks per module. You can see a usage example at MockoloTestCase:InitTests:testSimpleInitParams().  

Re: splitting public vs. internal -- we can address this; this has been in the backlog.

**Comment by FranzBusch** [comment]
Okay I see. I think having an option which allows to only take public protocols from certain dirs would be great. However I cannot imagine how this could be cleanly expressed in a command line arg. Have you thought about creating .yml config files?

I would also be open to implement some stuff.

**Comment by elsh** [comment]
It should already generate mocks for public protocols only when there are cross module dependencies. How are you running the tool?  Can you post your command line along with input args?  Sounds like it could be something that can be achieved by saving mock results per module, instead of all in one file.

**Comment by elsh** [comment]
> I would also be open to implement some stuff.
We would def. welcome that. Feel free to push a PR if this is something we agree on from this discussion or if you want us to have a look first.

**Comment by FranzBusch** [comment]
@elsh You are absolutely right using the generated mocks from another module work perfectly fine. I just used the wrong parameters/missed some annotations yesterday. I will close this issue. Thanks for your input!
