### ISSUE TITLE
Specify module to avoid type ambiguity

### ISSUE THREAD

**Issue by marciniwanicki** [uber/mockolo#95]
Protocols with the same name can be available in multiple modules, i.e. `FileSystem` and other common symbols. SwiftPM `FileSystem` is a good example:

```swift
import TSCBasic // part of SwiftPM, with public `FileSystem` protocol

// Here, my own FileSystem protocol

@mockable
public protocol FileSystem {
   // ...
}
```

The generated mock for `FileSystem` protocol will not compile due to type ambiguity (the compiler will not know if we want to inherit from SwiftPM `FileSystem` or the one in our Framework). 

One possible solution would be adding `module` attribute to `@mockable` annotation as such the generated mock could have more accurate inherit form `<module>.<protocol>` to avoid conflicts.

```swift
import TSCBasic // part of SwiftPM, with public `FileSystem` protocol

@mockable(module=MyFramework)
public protocol FileSystem {
   // ...
}
```

```swift
// GeneratedMocks.swift inside MyFrameworkMocks module

public class FileSytemMock: MyFramework.FileSystem {
   // ...
}

```

**Comment by elsh** [comment]
Yes this was on our todo list for a while; will add this.

**Comment by elsh** [comment]
https://github.com/uber/mockolo/pull/96
